Repository AY2324S1-CS2103T-F10-4/tp, pull requests merged in 2023-11, with the labels that each got.

#117 Modify UI: Add rounded corners for PersonCard and ScheduleCard
  src/main/java/seedu/address/ui/MainWindow.java
  src/main/java/seedu/address/ui/PersonCard.java
  src/main/resources/view/DarkTheme.css
  src/main/resources/view/PersonListCard.fxml
  src/main/resources/view/ScheduleCard.fxml
Labels: priority.low, type.Enhancement

#123 Update ug
  docs/UserGuide.md
  src/main/java/seedu/address/model/interval/IntervalEnd.java
Labels: documentation

#126 Modify UniquePersonList.java
  src/main/java/seedu/address/logic/commands/PaidCommand.java
  src/main/java/seedu/address/model/person/Person.java
  src/main/java/seedu/address/ui/PersonCard.java
  src/test/java/seedu/address/model/person/PersonTest.java
Labels: priority.high, type.Bug

#128 Modify addressbook.json to tuitionconnect.json
  src/main/java/seedu/address/model/UserPrefs.java
  src/test/data/JsonUserPrefsStorageTest/ExtraValuesUserPref.json
  src/test/data/JsonUserPrefsStorageTest/TypicalUserPref.json
  src/test/java/seedu/address/logic/LogicManagerTest.java
  src/test/java/seedu/address/storage/JsonUserPrefsStorageTest.java
Labels: type.Enhancement

#129 Modify UnPaidAllCommand and UnPaidCommand
  src/main/java/seedu/address/logic/commands/UnPaidAllCommand.java
  src/main/java/seedu/address/logic/commands/UnPaidCommand.java
Labels: enhancement

#133 Modify User Guide
  docs/UserGuide.md
Labels: documentation

#135 Bug Fix: Update help url
  src/main/java/seedu/address/logic/commands/RedoCommand.java
  src/main/java/seedu/address/logic/commands/UndoCommand.java
  src/main/java/seedu/address/ui/HelpWindow.java
Labels: type.Bug

#179 PE-D Bug Fixes
  docs/UserGuide.md
  docs/images/ClearCommand.png
  src/main/java/seedu/address/logic/commands/ClearCommand.java
Labels: priority.medium, type.Bug

#187 Modify DG: Update UI Class DIagram
  docs/DeveloperGuide.md
  docs/diagrams/UiClassDiagram.puml
  docs/images/UiClassDiagram.png
Labels: documentation

#181 Free time bug fix
  src/main/java/seedu/address/logic/commands/AddCommand.java
  src/main/java/seedu/address/logic/commands/FreeTimeCommand.java
  src/main/java/seedu/address/model/interval/Duration.java
  src/main/java/seedu/address/model/interval/TimeSlot.java
  src/test/java/seedu/address/logic/commands/AddCommandTest.java
  src/test/java/seedu/address/logic/commands/FreeTimeCommandTest.java
  src/test/java/seedu/address/model/interval/TimeSlotTest.java
  src/test/java/seedu/address/testutil/ModelStub.java
Labels: bug, documentation

#195 improve coding quality
  src/main/java/seedu/address/model/interval/IntervalBegin.java
  src/main/java/seedu/address/model/interval/IntervalEnd.java
  src/main/java/seedu/address/model/interval/TimeSlot.java
  src/main/java/seedu/address/model/person/Address.java
  src/main/java/seedu/address/model/person/Email.java
  src/main/java/seedu/address/model/person/Lesson.java
  src/main/java/seedu/address/model/person/Name.java
  src/main/java/seedu/address/model/person/Person.java
  src/main/java/seedu/address/model/person/Phone.java
  src/main/java/seedu/address/model/person/Subject.java
Labels: documentation

#201 Modify DG, PPP and Code Quality
  docs/DeveloperGuide.md
  docs/diagrams/AddActivityDiagram.puml
  docs/diagrams/ListByDaySequenceDiagram.puml
  docs/images/AddActivityDiagram.png
  docs/images/ListByDaySequenceDiagram.png
  docs/team/lambraydon.md
  src/main/java/seedu/address/model/interval/IntervalDay.java
  src/main/java/seedu/address/model/person/Day.java
  src/main/java/seedu/address/model/person/Person.java
  src/test/java/seedu/address/model/interval/IntervalDayTest.java
Labels: documentation

#207 Documentation
  docs/UserGuide.md
Labels: documentation

#204 Modify DG, Improve Code Quality
  docs/DeveloperGuide.md
  src/main/java/seedu/address/model/person/DayPredicate.java
  src/main/java/seedu/address/model/person/Lesson.java
  src/test/java/seedu/address/logic/commands/AddCommandTest.java
  src/test/java/seedu/address/logic/commands/EditCommandTest.java
  src/test/java/seedu/address/model/person/DayPredicateTest.java
  src/test/java/seedu/address/model/person/DayTest.java
Labels: documentation

#212 Documentation
  docs/DeveloperGuide.md
Labels: documentation

#214 Modify UG and DG
  docs/DeveloperGuide.md
  docs/UserGuide.md
Labels: documentation

#217 Modify UG: Add parameter table and Modify undo, redo & list
  docs/UserGuide.md
Labels: documentation

#221 Documentation
  docs/UserGuide.md
  docs/images/Add before and after.png
  docs/images/freeTime before and after.png
Labels: documentation

#224 Documentation
  docs/DeveloperGuide.md
  docs/diagrams/FreeTimeSequenceDiagram.puml
  docs/images/FreeTimeSequenceDiagram.png
Labels: documentation

#237 updated PPP
  docs/UserGuide.md
  docs/team/winstonleonard.md
Labels: documentation

#245 Update DG
  docs/DeveloperGuide.md
Labels: documentation
